<?xml version="1.0" encoding="utf-8"?>
<Database Name="AvsMask" Class="MaskDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLExpress;Initial Catalog=AvsMask;Integrated Security=True" SettingsObjectName="MeteorX.AssTools.KaraokeApp.Properties.Settings" SettingsPropertyName="AvsMaskConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Mask" Member="Masks">
    <Type Name="Mask">
      <Column Name="MaskId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlayResX" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlayResY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Style" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="X" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Y" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Str" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>